apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-manzi-mfa-db
  namespace: easyappointments
spec:
  schedule: {{ .Values.backupManziMfaDb.schedule }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            node-type: data-access
          containers:
          - name: mysql-dump-container
            image: mongulu/database-backup:latest
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: root
            - name: MYSQL_USER
              value: root
            - name: MYSQL_DATABASE
              value: easyappointments
            - name: MYSQL_HOST
              value: mysql
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: password
            - name: POSTGRES_USER
              value: avnadmin
            - name: POSTGRES_DATABASE
              value: manzi_mfa
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: host
            - name: POSTGRES_PORT
              value: "25661"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name:  awssm-secret
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name:  awssm-secret
                  key: secret-access-key

            command: ["sh", "-c"]
            args: 
            - |
              apt update &&apt install -y curl
              send_notification() {
                message=$1
                curl -X POST -H "Content-Type: application/json" \
                  -d "{\"text\":\"❌ $message\"}" \
                  https://eoqcnomqns2z3tq.m.pipedream.net
              }

              # Fonction pour gérer les erreurs
              handle_error() {
                error_message=$1
                send_notification "$error_message"
                exit 1
              }

              current_date=$(date "+%Y-%m-%d")
              snapshot_name="backup-$current_date.sql"

              {
                mysqldump -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE > "$snapshot_name"
                s4cmd put "$snapshot_name" s3://manzi-mfa/backup-db/$snapshot_name
              } || {
                handle_error "Échec de la sauvegarde MySQL pour $MYSQL_DATABASE le $current_date"
              }

              {
                PGPASSWORD=$POSTGRES_PASSWORD pg_dump -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DATABASE > "jobs-$snapshot_name"
                s4cmd put "jobs-$snapshot_name" s3://manzi-mfa/backup-db/jobs-$snapshot_name
              } || {
                handle_error "Échec de la sauvegarde PostgreSQL pour $POSTGRES_DATABASE le $current_date"
              }

          restartPolicy: OnFailure