apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-easyappointments
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvcEasyappointments.storage }}

