apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-credentials
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  #refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
  data:
  - secretKey: root
    remoteRef:
      key: /manzi-mfa/mysql/password

