apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-manzi-mfa-db
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-dump-container
            image: tsafacjo/mysql-dumb-aws:0.3
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: root
            - name: MYSQL_DATABASE
              value: easyappointments
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-host             
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: secret-access-key

            command: ["sh", "-c"]
            args:
            - |
              current_date=$(date "+%Y-%m-%d")
              snapshot_name="backup-$current_date.sql"
              mysqldump -h $MYSQL_HOST -u root -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE > "$snapshot_name"
              cat "$snapshot_name"
              aws s3 cp "$snapshot_name" s3://manzi-mfa/backup-db/$snapshot_name
          restartPolicy: OnFailure