AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  events-tracking
  Sample SAM Template for events_tracking
Parameters:

  # Environment variables
  easyAppointementsKey:
    Type: String
    NoEcho: true
  dbHost:
    Type: String
    NoEcho: true
  dbPort:
    Type: String
    NoEcho: true
  dbUser:
    Type: String
    NoEcho: true
  dbPassword:
    Type: String
    NoEcho: true   
  dbName:
    Type: String
    NoEcho: true    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 128

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  EventTrackingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: event-tracking/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        EventTracking:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: post
      Environment:
        Variables:
          easyAppointementsKey: !Ref easyAppointementsKey
          dbHost: !Ref dbHost
          dbPort: !Ref dbPort
          dbUser: !Ref dbUser
          dbPassword: !Ref dbPassword
          dbName: !Ref dbName
                                                
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EventTrackingApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  EventTrackingFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt EventTrackingFunction.Arn
  EventFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt EventTrackingFunctionRole.Arn
