apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-manzi-mfa-db
  namespace: easyappointments
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            node-type: data-access
          containers:
          - name: mysql-dump-container
            image: mongulu/mysql-data-backup:latest
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: root
            - name: MYSQL_USER
              value: root
            - name: MYSQL_DATABASE
              value: easyappointments
            - name: MYSQL_HOST
              value: mysql
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name:  awssm-secret
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name:  awssm-secret
                  key: secret-access-key

            command: ["sh", "-c"]
            args:
            - |
              apt update &&apt install -y curl
              send_notification() {
                message=$1
                curl -X POST -H "Content-Type: application/json" \
                  -d "{\"text\":\"❌ $message\"}" \
                  https://eoqcnomqns2z3tq.m.pipedream.net
              }

              # Fonction pour gérer les erreurs
              handle_error() {
                error_message=$1
                send_notification "$error_message"
                exit 1
              }

              current_date=$(date "+%Y-%m-%d")
              snapshot_name="backup-$current_date.sql"

              {
                mysqldump -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE > "$snapshot_name"
                aws s3 cp "$snapshot_name" s3://manzi-mfa/backup-db/$snapshot_name
              } || {
                handle_error "Échec de la sauvegarde MySQL pour $MYSQL_DATABASE le $current_date"
              }
          restartPolicy: OnFailure
