apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-manzi-mfa-db
  namespace: easyappointments
spec:
  schedule: "0 0 * * *" 
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            node-type: data-access
          containers:
          - name: mysql-dump-container
            image: mongulu/mysql-data-backup:latest
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: root
            - name: MYSQL_USER
              value: root
            - name: MYSQL_DATABASE
              value: easyappointments              
            - name: MYSQL_HOST
              value: mysql             
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name:  awssm-secret
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name:  awssm-secret
                  key: secret-access-key

            command: ["sh", "-c"]
            args:
            - |
              current_date=$(date "+%Y-%m-%d")
              snapshot_name="backup-$current_date.sql"
              echo $MYSQL_HOST
              echo $MYSQL_ROOT_PASSWORD
              echo $MYSQL_DATABASE
              mysqldump -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE > "$snapshot_name"
              aws s3 cp "$snapshot_name" s3://manzi-mfa/backup-db/$snapshot_name
          restartPolicy: OnFailure
