name: tsafacjo/mysql-dumb-aws:latest 

on:
  push:
    branches:
      - main
      - feat/mysqlbackup_on_s3
    paths:
      - 'database/**'
      - '.github/workflows/deploy_mysql_dumb_image.yml'
jobs:
  build:
    runs-on: arc-runner-set

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      run: |
        pwd
        ls
        docker  build -t tsafacjo/mysql-dumb-aws:latest   --platform  linux/arm/v7  database/backup/docker 
        echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
        docker push tsafacjo/mysql-dumb-aws:latest
      env:
        DOCKER_CLI_AGGREGATE: 1
