name: tsafacjo/mysql-dumb-aws:latest 

on:
  push:
    branches:
      - main
      - feat/mysqlbackup_on_s3
    paths:
      - 'database/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build -t tsafacjo/mysql-dumb-aws:latest  -f database/backup/docker  --platform linux/arm64 .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push your-docker-registry/your-image-name:latest
      env:
        DOCKER_CLI_AGGREGATE: 1
