name: Deploy Lambda with SAM

on:
  push:
    #paths:
    #  - 'data_ingestion/events_tracking/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  # Replace with your desired AWS region
          
      - name: Deploy Lambda
        run: |  
            echo | pwd
            ls
            cd data_ingestion/events_tracking
            echo | pwd
            sam deploy  --parameter-overrides "EASY_APPOINTMENTS_KEY=${{ secrets.EASY_APPOINTMENTS_KEY }} DB_HOST=${{ secrets.DB_HOST }}  DB_PORT=${{ secrets.DB_PORT }}  DB_USER=${{ secrets.DB_USER }}  DB_PASSWORD=${{ secrets.DB_PASSWORD }}  DB_NAME=${{ secrets.DB_NAME }}"
